[package]
name = "sim_kernel"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
kernel_api.workspace = true
core_types.workspace = true
ipc.workspace = true
serde.workspace = true
