[package]
name = "resources"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true, default-features = false, features = ["derive", "alloc"] }

[dev-dependencies]
