[package]
name = "lifecycle"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
kernel_api = { workspace = true }
serde = { workspace = true, default-features = false, features = ["derive", "alloc"] }
