[package]
name = "contract_tests"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
core_types = { workspace = true }
ipc = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
