[package]
name = "packages"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
resources = { workspace = true }
serde = { workspace = true, features = ["std"] }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = "3"
